eureka:
  client:
    service-url:
     defaultZone: http://${other.eureka.hostname}:${other.eureka.port}/eureka
  server:
    enable-self-preservation: false
---
spring:
 profiles: eureka1
 application:
  name: eureka1

eureka:
 instance:
  hostname: localhost

server:
 port: 8761

other:
 eureka:
  hostname: localhost
  port: 8762

---
spring:
  profiles: eureka2
  application:
   name: eureka2

server:
 port: 8762

eureka:
  instance:
    hostname: localhost

other:
 eureka:
  hostname: localhost
  port: 8761
  

 
