spring:
  application:
    name: Book-Service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
                   
                  


---
spring:
  profiles: book1
  datasource:
    password: ''
    url: jdbc:mysql://localhost:3306/microDb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081



---
spring:
  profiles: book2
  datasource:
    password: ''
    url: jdbc:mysql://localhost:3306/microDb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082


  
